In [1]:
import numpy as np

In [2]:
arreglo = np.array([1,2,3,4,5,6])

In [3]:
type(arreglo)

numpy.ndarray

In [4]:
arreglo

array([1, 2, 3, 4, 5, 6])

In [5]:
arreglo2 = np.array([1.3,2.6,3,4,5,6])

In [7]:
arreglo2.dtype

dtype('float64')

In [19]:
arreglo2.ndim

1

In [21]:
arreglo2.shape

(6,)

In [8]:
arreglo3 = np.array([1.3,2.6,3,'a','b',6])

In [10]:
arreglo3.dtype

dtype('<U32')

In [16]:
arreglo = np.array([[1,2,3,4,5,6],[3,4,5,6,7,8]])

In [17]:
arreglo

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7, 8]])

In [18]:
arreglo.ndim

2

In [20]:
arreglo.shape

(2, 6)

In [22]:
arreglo.size

12

In [25]:
for fila in arreglo:
    print(fila)
    for columna in fila:
        print(columna, end='; ')
    print()

[1 2 3 4 5 6]
1; 2; 3; 4; 5; 6; 
[3 4 5 6 7 8]
3; 4; 5; 6; 7; 8; 


In [27]:
for elemento in arreglo.flat:
    print(elemento, end=' ')

1 2 3 4 5 6 3 4 5 6 7 8 

In [28]:
ceros = np.zeros(6)

In [29]:
ceros

array([0., 0., 0., 0., 0., 0.])

In [30]:
unos = np.ones((3,4))

In [31]:
unos

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
unos = np.ones((3,4), dtype=int)

In [33]:
unos

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [34]:
completo = np.full((2,4), 9)

In [35]:
completo

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

In [37]:
np.linspace(0.5, 1, num=10)

array([0.5       , 0.55555556, 0.61111111, 0.66666667, 0.72222222,
       0.77777778, 0.83333333, 0.88888889, 0.94444444, 1.        ])

In [44]:
n = np.arange(1,21).reshape(2,10) # Crear un arreglo de dos filas y 10 columnas. Los valores van a ser del 1 al 20

In [45]:
n

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [49]:
n2 = n*3
print(n2)

[[ 3  6  9 12 15 18 21 24 27 30]
 [33 36 39 42 45 48 51 54 57 60]]


In [50]:
n + n2

array([[ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40],
       [44, 48, 52, 56, 60, 64, 68, 72, 76, 80]])

In [51]:
n <= 10

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [53]:
n1 = np.array([1,2,3,4])
n2 = np.array([10,2,3,40])

In [54]:
n1 < n2

array([ True, False, False,  True])

In [55]:
n1 == n2

array([False,  True,  True, False])

In [56]:
n1 = np.array([[1,2,3,4], [10,2,3,40]])

In [57]:
n1

array([[ 1,  2,  3,  4],
       [10,  2,  3, 40]])

In [58]:
n1.sum(axis = 0)

array([11,  4,  6, 44])

In [59]:
n1.sum(axis = 1)

array([10, 55])

In [60]:
n1.mean(axis = 0)

array([ 5.5,  2. ,  3. , 22. ])

In [61]:
n1.mean(axis = 1)

array([ 2.5 , 13.75])

In [62]:
n1 = np.array([1,2,3,4])

In [63]:
len(n1)

4

In [64]:
n1.size

4

In [65]:
n1[0]

1

In [66]:
n1[0]=100

In [67]:
n1

array([100,   2,   3,   4])

In [68]:
n = np.arange(1,21).reshape(2,10)

In [69]:
len(n)

2

In [70]:
n.size

20

In [72]:
n.shape

(2, 10)

In [73]:
n

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [74]:
n[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
n[0][9]

10

In [77]:
x = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0]])

In [79]:
x.dtype

dtype('float64')

In [80]:
x[0].dtype

dtype('float64')

In [82]:
x[0][1].dtype

dtype('float64')

In [83]:
x[0]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [85]:
x[0][1:6]

array([2., 3., 4., 5., 6.])

In [86]:
x

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.]])

In [89]:
x = x.T

In [91]:
x

array([[ 1., 11.],
       [ 2., 12.],
       [ 3., 13.],
       [ 4., 14.],
       [ 5., 15.],
       [ 6., 16.],
       [ 7., 17.],
       [ 8., 18.],
       [ 9., 19.],
       [10., 20.]])

In [93]:
x[1:6, 1]

array([12., 13., 14., 15., 16.])

In [7]:
n1 = np.arange(1,11).reshape(2,5)

In [8]:
n1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
n2 = np.array([2,2,2,2,4])

In [10]:
n3 = n1 * n2

In [11]:
n3

array([[ 2,  4,  6,  8, 20],
       [12, 14, 16, 18, 40]])

In [100]:
np.sqrt(n3)

array([[1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766],
       [3.46410162, 3.74165739, 4.        , 4.24264069, 4.47213595]])

In [102]:
np.power(n3, 2)

array([[  4,  16,  36,  64, 100],
       [144, 196, 256, 324, 400]])

In [12]:
n1 = np.array([[ 10,  2,  3,  4,  5],
               [ 60,  7,  8,  9, 10]])

In [13]:
np.minimum(n3, n1) #element-wise

array([[ 2,  2,  3,  4,  5],
       [12,  7,  8,  9, 10]])

In [106]:
n3

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [107]:
n3[0]=[3,6,9,12,15]

In [108]:
n3

array([[ 3,  6,  9, 12, 15],
       [12, 14, 16, 18, 20]])

In [109]:
n3[:,[0,2,4]]

array([[ 3,  9, 15],
       [12, 16, 20]])

In [110]:
np.min(n3)

3

In [111]:
np.min(n3, axis = 0)

array([ 3,  6,  9, 12, 15])

In [112]:
np.min(n3, axis = 1)

array([ 3, 12])

In [116]:
dimens = np.array([[[ 3,  6,  9, 12, 15],
                   [12, 14, 16, 18, 20]],
                  [[ 3,  6,  9, 12, 15],
                   [12, 14, 16, 18, 20]]])

In [117]:
dimens

array([[[ 3,  6,  9, 12, 15],
        [12, 14, 16, 18, 20]],

       [[ 3,  6,  9, 12, 15],
        [12, 14, 16, 18, 20]]])

In [118]:
dimens.shape

(2, 2, 5)

In [119]:
dimens[0]

array([[ 3,  6,  9, 12, 15],
       [12, 14, 16, 18, 20]])

In [120]:
dimens[0][0]

array([ 3,  6,  9, 12, 15])

In [121]:
dimens[0][0][0]

3

In [14]:
n = np.arange(1,21).reshape(2,2,5)

In [15]:
n

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])